---
baseURL: https://geekdocs.de/
title: AirOne
theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true
timeout: 180000

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

params:
  geekdocToC: 3
  geekdocLogo: /media/logo.png

  geekdocRepo: https://github.com/thegeeklab/hugo-geekdoc
  geekdocEditPath: edit/master/exampleSite/content

  geekdocSearch: true
